# Generated by Django 6.0.2 on 2026-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('content', models.TextField(max_length=4000, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена товара')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
