# Generated by Django 6.0.2 on 2026-03-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_info',
            field=models.CharField(default='', max_length=255, verbose_name='Контактная информация'),
            preserve_default=False,
        ),
    ]
